name: Build My APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Install dependencies
        run: yarn install

      - name: Create fake google-services.json
        run: |
          echo '{"project_info":{"project_number":"123","project_id":"dummy"},"client":[{"client_info":{"mobilesdk_app_id":"1:123:android:abc","android_client_info":{"package_name":"com.pocketpal"}},"api_key":[{"current_key":"dummy"}]}]}' > android/app/google-services.json
        
      - name: Build Debug APK
        working-directory: android
        run: ./gradlew assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pocketpal-app-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
          
